### ISSUE TITLE
Type as array support

### ISSUE THREAD

**Issue by StayClassic** [json-schema-tools/transpiler#178]
In JSON Schema, a type field may be specified as either a string, or an array of strings.

In effect, it is the same thing as using `oneOf`. ATM the transpiler does not have good support for this, and returns things as untyped (becomes the 'any' type). 

The proposed solution is to pre-process the input json schema, turning all schemas and subschemas which have the use of `type: []` into a schema + subschemas that use `oneOf` instead. The end result is that types are generated for the schema, and the user never becomes aware that the `type: []` is internally converted to `oneOf`.

**Comment by BelfordZ** [comment]
this has been finished and released.
