### ISSUE TITLE
should support patternProperties

### ISSUE THREAD

**Issue by shanejonas** [json-schema-tools/transpiler#75]
**Describe the bug**
should support patternProperties

**To Reproduce**
Create a schema with a patternProperty and try to use it

![image](https://user-images.githubusercontent.com/364566/88578701-ceb70d80-cffd-11ea-830a-ac28c4ea9b4d.png)

**Expected behavior**
should provide valid types

**Additional Screenshots**

snippet of schema:

![image](https://user-images.githubusercontent.com/364566/88578848-07ef7d80-cffe-11ea-9c7b-cd01e8a610e9.png)

**Comment by BelfordZ** [comment]
done!
